### ISSUE TITLE
Comment on pros and cons of WebSocket API

### ISSUE THREAD

**Issue by efim-poberezkin** [simplex-chat/protocol#27]
\+ no need for polling, hence messages can be pushed from server to receiver
\- possible to correlate connections that are in the same session
\- use via Tor (?)

maybe also that "send" via WS for active conversations would be premature optimization, that's why there's only "receive" API

**Comment by epoberezkin** [comment]
TCP is now the default transport, with fallback to websockets or long polling only for web clients.
