### ISSUE TITLE
Describe how to check for MITM between the server and the receiver

### ISSUE THREAD

**Issue by efim-poberezkin** [simplex-chat/protocol#31]
Receiver can check for MITM between him and his server by asking the real sender to test a request signed by the receiver on the receiver's server via sender's URI (that is via a specific endpoint). This signed request can be passed to the sender:
- either via initial QR
- or via a duplicate simplex (this can be done on a regular basis as a preventive measure)

Or we can do both.

As a sidenote,
There can be no MITM between *the sender* and the receiver's server because sender's key (SK) is saved on the server by the receiver via signed request.

**Comment by epoberezkin** [comment]
added transport connection as a separate pre-requisite.
