### ISSUE TITLE
Please clarify the 'problems' listed in readme

### ISSUE THREAD

**Issue by papb** [simplex-chat/protocol#37]
> ## Problems
> 
> Existing chat platforms and protocols have some or all of the following problems:
> - privacy of the conversation, partially caused by E2EE implementations.
> - privacy of the user profile and connections.

Why is privacy a problem?

**Comment by epoberezkin** [comment]
Lack of privacy is a problem of course :)

**Comment by epoberezkin** [comment]
updated

**Comment by papb** [comment]
Why is lack of privacy "partially caused by E2EE implementations"? Shouldn't E2EE fix this exact problem?

**Comment by epoberezkin** [comment]
The problem of E2EE implementations is that there is always a 3rd party between communicating parties that mediates the initial key exchange - this party can substitute the key. There is a picture on the website about it...
